sudo: required
services:
  - docker
script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=$DOCKER_USER/k8s-ha-ansible-docker
  - export TAG=latest
  - docker build -t gr0unz/k8s-ha-ansible-docker .
  - docker tag gr0unz/k8s-ha-ansible-docker gr0unz/k8s-ha-ansible-docker:$TAG
  - docker push $REPO
