apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
{% if ansible_hostname == "{{ hostname_master_1 }}" %}
api:
  advertiseAddress: {{ master_1_ip }}
{% endif %}
{% if ansible_hostname == "{{ hostname_master_2 }}" %}
api:
  advertiseAddress: {{ master_2_ip }}
{% endif %}
{% if ansible_hostname == "{{ hostname_master_3 }}" %}
api:
  advertiseAddress: {{ master_3_ip }}
{% endif %}
etcd:
  endpoints:
  - https://{{ master_1_ip }}:2379
  - https://{{ master_2_ip }}:2379
  - https://{{ master_3_ip }}:2379
  caFile: /etc/kubernetes/pki/etcd/ca.pem
  certFile: /etc/kubernetes/pki/etcd/client.pem
  keyFile: /etc/kubernetes/pki/etcd/client-key.pem
networking:
  podSubnet: {{ pod_network_cidr }}
apiServerCertSANs:
- {{ virtual_ip }}
apiServerExtraArgs:
  apiserver-count: "3"
