apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
api:
  advertiseAddress: {{ ansible_default_ipv4.address }}
etcd:
  endpoints:
  - https://{{ master_1_ip }}:2379
  - https://{{ master_2_ip }}:2379
  - https://{{ master_3_ip }}:2379
  caFile: /etc/kubernetes/pki/etcd/ca.pem
  certFile: /etc/kubernetes/pki/etcd/client.pem
  keyFile: /etc/kubernetes/pki/etcd/client-key.pem
networking:
  podSubnet: {{ pod_network_cidr }}
apiServerCertSANs:
- {{ virtual_ip }}
apiServerExtraArgs:
  apiserver-count: "3"
